spring.application.name=cadastro-empresa-relacional
spring.datasource.username=mafe
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/cadastro_empresa
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration